name: Rails

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      - name: Install dependencies
        run: bundle install
      - name: Setup database
        run: rails db:test:prepare
      - name: Migrate database
        run: rails db:migrate
      - name: Run tests
        run: bundle exec rake
